language: node_js
node_js:
    - "0.12"
before_install:
- npm install -g hexo

install:
- npm install
- npm install hexo-renderer-mathjax --save

before_script:
    - git config --global user.name 'NatruaAurum via Travis CI'
    - git config --global user.email 'natura0321@gmail.com'
    #- sed -i'' "s~git@github.com:NaturaAurum/Blog.git~https://${GH_TOKEN}:x-oauth-basic@github.com/NaturaAurum/Blog.git~" _config.yml
    
script:
    - hexo generate
    
after_success:
    #- mkdir .deploy
    #- cd .deploy
    #- git init
    #- git remote add origin $DEPLOY_REPO
    #- cp -r ../public/* .
    #- git add -A .
    #- git commit -m 'Content Updated'
    #- git push --force --quiet origin master
    - hexo deploy